### ISSUE TITLE
Unable to open,  close or toggle garage door but correctly shows status of OpenGarage unit; get error 404 

### ISSUE THREAD

**Issue by TomMcBride** [thebearmay/hubitat#11]
I loaded this  Driver code to my Hubitat and created a new device. Everything seems OK except that I get a 404 error when trying to open, close or toggle my garage door. Viewing the device shows correct information for the status of the door and presence/absence of my vehicle. I modified one line of the code to log exactly what is being sent to open the door and the log shows that the correct data is being used. This is the line I changed:

    if(txtEnable) log.info "opening relay... http://$devIP/cc?dkey=$devPwd&open=1"

The garage door operates as expected if I type the http command into my browser. I'm attaching a couple of screenshots that show my device definition and some of the log data after I tried clicking open, close and toggle on the device definition page. Any suggestions would be welcome.
![HubitatGarage-1](https://github.com/thebearmay/hubitat/assets/10499802/d8ee68d1-e999-4bc3-b3f9-01d54551a1d1)
![HubitatGarage-2](https://github.com/thebearmay/hubitat/assets/10499802/04a25c7e-40cd-40a6-8930-dc6aba1acf9f)

**Comment by thebearmay** [comment]
404 is a pathing error, and given that when you manually type in the command it works, I’d have to conclude that the IP address in the preference has become corrupted and now contains an unprintable character.  Try clicking into the prefence field hitting Ctrl-A, delete the field contents, and re-entering (making sure that there are no leading or trailing spaces).

**Comment by TomMcBride** [comment]
Thanks for taking the time to look at this problem. I’m pretty certain that the values entered in preferences is correct. I have it working fine right now. I changed the httpGet() call as follows:

Original code for open():

            uri: "http://$devIP",
            path: "/cc?dkey=$devPwd&open=1”,

My change:

            uri: "http://$devIP/cc?dkey=$devPwd&open=1",
            //path: "/cc?dkey=$devPwd&open=1”,

As you can see, I basically constructed the entire command in the uri parameter instead of letting httpGet() put uri and path  together and then commented out the line with the path parameter. I made the same change for close() and  toggleDoor(); all now work perfectly and all produced the 404 error before. I haven’t changed rebootDevice() yet … I haven’t tried to reboot the device … though I could test that if you want. I did not make a similar change to the poll() function which has always seemed to work perfectly. If httpGet() is inserting some character that caused the error, I would have expected poll() to fail as well but it does not. I don’t think I’ve changed the IP address or password in preferences since I first entered them but your suggestion made me think that I might have done that at some point in my testing. I just changed the code back to the original for toggleDoor() and tried it. I got this in the log:

dev:225 <http://192.168.86.100/logs?tab=past&deviceId=225#>2023-11-18 08:15:33.416 AMerror <http://192.168.86.100/logs?tab=past&deviceId=225#>groovyx.net.http.HttpResponseException: status code: 404, reason phrase: Not found on line 117 (method toggleDoor)

I then changed the code back to what I had and it worked correctly.

This driver is written in Groovy and that is a language I previously knew nothing about. Perhaps there is some way to log the exactly what httpGet is sending to figure out what’s wrong but I couldn’t find any way to do that.

The other minor change I made was to increase the value you had in  runIn(10,"poll”) to 30 seconds; my garage door takes longer than 10 seconds to move though it doesn’t take a full 30 seconds; I should just time it and lower the 30 but haven’t done that yet.

If I can help by making changes and running tests for you, I’m willing to do that.

Tom
