### ISSUE TITLE
Suggestion: Maker API call round-trip timer

### ISSUE THREAD

**Issue by LibraSun** [thebearmay/hubitat#6]
This is 99% conceptual and 1% practical, but do you see any value in adding a feature to Hubitat Hub Information driver which periodically checks the time (in ms) to receive a response from Maker API after sending it a local GET?

I'm unsure how much variance there is on these round trips, but I've always wondered, especially because it has become the de facto method for connecting external apps, in lieu of WebSockets.

**Comment by thebearmay** [comment]
I could see writing some type of ping utility for it, but probably not in the Information Driver.  Easiest way to implement might be to create a virtual switch and a NodeRed responder.  Measure the time from when the switch is toggled to the time NR-MakerAPI turns it off.  Could then also have it run on a schedule to generate values that could be graphed or....

**Comment by thebearmay** [comment]
Just realized I have a stopwatch device already written (stopwatch.groovy).  So I created a Node Red flow to turn off Timer 1 (it has 5) when it receives notice that it's been turned on.  The Duration reported is in milliseconds.

Node Red JSON:
[
    {
        "id": "d8ab23466385eec4",
        "type": "hubitat device",
        "z": "195f141e.c79f8c",
        "deviceLabel": "!stopWatch",
        "name": "",
        "server": "2731734d1544bcd1",
        "deviceId": "62",
        "attribute": "start1",
        "sendEvent": true,
        "x": 170,
        "y": 1400,
        "wires": [
            [
                "0e9e36acf7d67979"
            ]
        ]
    },
    {
        "id": "0e9e36acf7d67979",
        "type": "hubitat command",
        "z": "195f141e.c79f8c",
        "deviceLabel": "!stopWatch",
        "name": "",
        "server": "2731734d1544bcd1",
        "deviceId": "62",
        "command": "stopTimer",
        "commandArgs": "1",
        "x": 370,
        "y": 1400,
        "wires": [
            []
        ]
    },
    {
        "id": "2731734d1544bcd1",
        "type": "hubitat config",
        "name": "Hubitat Development",
        "usetls": false,
        "host": "192.168.1.3",
        "port": "80",
        "appId": "5",
        "nodeRedServer": "http://192.168.1.2:6335",
        "webhookPath": "/hubitat/webhook_",
        "autoRefresh": true,
        "useWebsocket": false,
        "colorEnabled": false,
        "color": "#ace043"
    }
]

Could set up a rule to _Start Timer 1_ on a routine basis and then grab _duration1_ for graphing or charting.  Just playing I'm seeing a round trip of 60ms - 133ms
