### ISSUE TITLE
Suggestion: Enumerate "Rooms" and "Room Images"

### ISSUE THREAD

**Issue by LibraSun** [thebearmay/hubitat#7]
Didn't think I'd be back so soon to make another out-of-left-field suggestion, but would it be possible for Hub Information Device to include a list of all declared Rooms on HE, along with their assigned image, if present?

Naturally, this would be a feature your users could toggle on/off as they do with other sensitive info.

Thoughts? I was honestly quite surprised to discover that Maker API doesn't natively share (pass or poll) "Rooms", unless an authorized device happens to be assigned to a Room. Thus empty rooms are entirely missed; and, so far, nothing outside of Groovy or Settings > Rooms appears to have access to Room Images. Not even sure where HE intended them to "go" at this point.

**Comment by thebearmay** [comment]
Hubitat hasn't exposed the construct for their rooms implementation yet.  We can see the manifestation of it in the device structures, and the mobile apps, so we know it exists, but a good way to query it isn't available.  That being said, I have a few ideas on how I could back into a listing of rooms and attributes.  Might have some time to look at this later in the week.

**Comment by thebearmay** [comment]
Created a new device driver - roomInfo.groovy.  It will read the Rooms page and parse it into a JSON string that contains a summary of what was found.  Given that rooms and devices don't change too often I've defaulted the poll refresh rate to 1440 minutes (24 hours) and at hub restart.  JSON is based on the Room ID Number, but has attributes for the name, device list and whether an image is attached.  Path to the room image is http://hubIpAddress/room/image/Room_Number, but I've also created a command to return the path in an img tag

**Comment by LibraSun** [comment]
Too cool for school! I've always been one of your biggest fans, and this reminds me why.
THANKS!
P.S. Would the dev community benefit long-term from having "Rooms" info available directly through hub polling or Maker API? (i.e. instead of having to roll your own) I'd love to know what HE staff have to say about it.
